import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//  };
const sidebars = {
  tutorialSidebar: [
    'motivation',
    'functionality',
    {
      type: 'category',
      label: 'Installation',
      link: { type: 'doc', id: 'installation/index' },
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Standard',
          link: { type: 'doc', id: 'installation/standard/index' },
          items: [
            'installation/standard/aws',
            'installation/standard/azure',
            'installation/standard/gcp',
          ],
        },
        {
          type: 'category',
          label: 'Terraform',
          link: { type: 'doc', id: 'installation/terraform/index' },
          items: [
            'installation/terraform/aws',
            'installation/terraform/azure',
            'installation/terraform/gcp',
          ],
        },
      ],
    },
    'usage',
    'faq',
    'troubleshooting',
  ],
};

export default sidebars;

