# Databricks notebook source
# MAGIC %md
# MAGIC **Functionality:** Analyzes all configured workspaces and generates a report of hardcoded secrets.

# COMMAND ----------

# MAGIC %run ./diagnosis/pre_run_config_check

# COMMAND ----------

# MAGIC %run ./Includes/install_sat_sdk

# COMMAND ----------

# MAGIC %run ./Utils/initialize

# COMMAND ----------

# MAGIC %run ./Utils/common

# COMMAND ----------

hostname = (
    dbutils.notebook.entry_point.getDbutils()
    .notebook()
    .getContext()
    .apiUrl()
    .getOrElse(None)
)
cloud_type = getCloudType(hostname)
clusterid = spark.conf.get("spark.databricks.clusterUsageTags.clusterId")
json_.update(
    {
        "url": hostname,
        "workspace_id": "accounts",
        "cloud_type": cloud_type,
        "clusterid": clusterid,
    }
)

# COMMAND ----------

dfexist = getWorkspaceConfig()
dfexist.filter(dfexist.analysis_enabled == True ).createOrReplaceTempView(
    "all_workspaces"
)

# COMMAND ----------

import json
from dbruntime.databricks_repl_context import get_context
current_workspace = get_context().workspaceId

# COMMAND ----------

# MAGIC %md
# MAGIC ##### The analysis executes across all Databricks workspaces configured for SAT. Eligible workspaces are determined based on entries in **`workspace_configs.csv`** and the **`security_analysis.account_workspaces`** table where the **`analysis_enabled`** flag is set to **`True`**.
# MAGIC ##### If a workspace does not appear in the results, verify that it is correctly listed and that **`analysis_enabled = True`** in both configuration sources.
# MAGIC ##### When running the job/notebook using **Serverless Compute**, the analysis is limited to the **current workspace**. To scan all eligible workspaces, use a Classic Compute cluster.

# COMMAND ----------

serverless_filter=""
if is_serverless:
    serverless_filter = " where workspace_id = '" + current_workspace + "'"

workspacesdf = spark.sql(f"select * from `all_workspaces` {serverless_filter}")
display(workspacesdf)
workspaces = workspacesdf.collect()
if workspaces is None or len(workspaces) == 0:
    loggr.info(
        "Workspaces are not configured for analysis, check the workspace_configs.csv and "
        + json_["analysis_schema_name"]
        + ".account_workspaces if analysis_enabled flag is enabled to True. Use security_analysis_initializer to auto configure workspaces for analysis. "
    )
    # dbutils.notebook.exit("Unsuccessful analysis.")

# COMMAND ----------

# MAGIC %md
# MAGIC ### TruffleHog Secret Scanning
# MAGIC ##### Runs TruffleHog secret scanning across all configured workspaces to detect exposed credentials and secrets in notebooks.

# COMMAND ----------

def generate_shared_run_id():
    """
    Generate a shared run_id for both notebook and cluster scans.
    This enables correlation between findings in the same scan run.

    Returns:
        int: New run ID (auto-generated by IDENTITY column)
    """
    try:
        # Insert new run into run_number_table (runID is auto-generated as IDENTITY column)
        spark.sql(f'''
            INSERT INTO {json_["analysis_schema_name"]}.run_number_table (check_time)
            VALUES (current_timestamp())
        ''')

        # Retrieve the auto-generated runID (it will be the max value)
        result = spark.sql(f'''
            SELECT max(runID) as new_run_id
            FROM {json_["analysis_schema_name"]}.run_number_table
        ''').collect()

        new_run_id = result[0]["new_run_id"]
        loggr.info(f"Generated shared run_id: {new_run_id}")
        return new_run_id

    except Exception as e:
        loggr.error(f"Failed to generate shared run_id: {str(e)}")
        # Fallback: use current timestamp as unique run ID
        import time
        fallback_run_id = int(time.time())
        loggr.info(f"Using fallback run_id: {fallback_run_id}")
        return fallback_run_id


def processTruffleHogScan(wsrow, run_id):
    """
    Process TruffleHog secret scanning for a single workspace.
    Similar to processWorkspace but focused on secrets detection.

    Args:
        wsrow: Workspace row with configuration
        run_id: Shared run ID for this scan run
    """
    import json

    hostname = "https://" + wsrow.deployment_url
    cloud_type = getCloudType(hostname)
    workspace_id = wsrow.workspace_id
    clusterid = spark.conf.get("spark.databricks.clusterUsageTags.clusterId")
    ws_json = dict(json_)
    ws_json.update(
        {
            "url": hostname,
            "workspace_id": workspace_id,
            "cloud_type": cloud_type,
            "clusterid": clusterid,
            "run_id": run_id,  # Add shared run_id
        }
    )

    loggr.info(f"Starting notebook scan for workspace: {workspace_id} (run_id: {run_id})")
    loggr.info(ws_json)

    # Run TruffleHog secret scanning for notebooks
    loggr.info(f"Running TruffleHog notebook scan for workspace: {workspace_id}")
    scan_result = dbutils.notebook.run(
        f"{basePath()}/notebooks/Includes/scan_secrets/notebook_secret_scan",
        14400,  # 4 hour timeout for secrets scanning
        {"json_": json.dumps(ws_json)},
    )
    loggr.info(f"Notebook scan completed for workspace: {workspace_id}")
    return scan_result


def processClusterScan(wsrow, run_id):
    """
    Process cluster configuration secret scanning for a single workspace.

    Args:
        wsrow: Workspace row with configuration
        run_id: Shared run ID for this scan run (same as notebook scan)

    Returns:
        str: JSON result from cluster scan
    """
    import json

    hostname = "https://" + wsrow.deployment_url
    cloud_type = getCloudType(hostname)
    workspace_id = wsrow.workspace_id

    clusterid = spark.conf.get("spark.databricks.clusterUsageTags.clusterId")
    ws_json = dict(json_)
    ws_json.update(
        {
            "url": hostname,
            "workspace_id": workspace_id,
            "cloud_type": cloud_type,
            "clusterid": clusterid,
            "run_id": run_id,  # Add shared run_id
        }
    )

    loggr.info(f"Starting cluster scan for workspace: {workspace_id} (run_id: {run_id})")

    # Run cluster configuration secret scanning
    loggr.info(f"Running cluster config scan for workspace: {workspace_id}")
    scan_result = dbutils.notebook.run(
        f"{basePath()}/notebooks/Includes/scan_secrets/cluster_secrets_scan",
        14400,  # 4 hour timeout for cluster scanning
        {"json_": json.dumps(ws_json)},
    )
    loggr.info(f"Cluster scan completed for workspace: {workspace_id}")
    return scan_result


def runTruffleHogScanForAllWorkspaces():
    """
    Run secret scanning (notebooks + clusters) for all configured workspaces.
    Each workspace gets a shared run_id for correlation between notebook and cluster findings.

    Workspaces are scanned concurrently, and within each workspace the notebook
    and cluster scans run concurrently. Degree of cross-workspace parallelism is
    controlled by `secrets_max_parallel_workspaces` (default 4). A scan failure
    in one workspace is logged and does not stop the others.
    """
    import concurrent.futures

    loggr.info("Starting secret scanning for all configured workspaces")

    scan_workspaces = workspaces

    if scan_workspaces is None or len(scan_workspaces) == 0:
        loggr.info("No workspaces configured for secret scanning")
        return

    loggr.info(f"Running secret scans on {len(scan_workspaces)} workspace(s)")

    # Pre-allocate a shared run_id per workspace sequentially on the main thread.
    # generate_shared_run_id() does INSERT + SELECT max(runID), which would race
    # under concurrency (two workspaces could read the same max), so it must run
    # before the parallel fan-out.
    ws_run_ids = [(ws, generate_shared_run_id()) for ws in scan_workspaces]

    def scan_one_workspace(ws, shared_run_id):
        loggr.info(f"Starting scans for workspace: {ws.workspace_id} (run_id: {shared_run_id})")
        print(f"🔍 Starting scans for workspace: {ws.workspace_id} (run_id: {shared_run_id})")

        # Scan failures for this workspace, surfaced in the final summary.
        local_failures = []

        def notebook_scan():
            try:
                processTruffleHogScan(ws, shared_run_id)
                loggr.info(f"Notebook scan completed for workspace: {ws.workspace_id}")
                print(f"  ✅ Notebook scan completed for {ws.workspace_id}")
            except Exception as e:
                loggr.error(f"Notebook scan failed for workspace {ws.workspace_id}: {str(e)}")
                print(f"  ❌ Notebook scan failed for {ws.workspace_id}: {str(e)}")
                local_failures.append(f"{ws.workspace_id}/notebooks: {str(e)}")

        def cluster_scan():
            try:
                processClusterScan(ws, shared_run_id)
                loggr.info(f"Cluster scan completed for workspace: {ws.workspace_id}")
                print(f"  ✅ Cluster scan completed for {ws.workspace_id}")
            except Exception as e:
                loggr.error(f"Cluster scan failed for workspace {ws.workspace_id}: {str(e)}")
                print(f"  ❌ Cluster scan failed for {ws.workspace_id}: {str(e)}")
                local_failures.append(f"{ws.workspace_id}/clusters: {str(e)}")

        # Notebook and cluster scans are independent — run them concurrently.
        with concurrent.futures.ThreadPoolExecutor(max_workers=2) as inner:
            for f in [inner.submit(notebook_scan), inner.submit(cluster_scan)]:
                f.result()
        if local_failures:
            print(f"⚠️  Scans finished WITH FAILURES for workspace: {ws.workspace_id}")
        else:
            print(f"✅ All scans completed for workspace: {ws.workspace_id}")
        return local_failures

    max_parallel = max(1, int(json_.get("secrets_max_parallel_workspaces", 4)))
    max_parallel = min(max_parallel, len(ws_run_ids))
    loggr.info(f"Scanning up to {max_parallel} workspace(s) in parallel")

    # One workspace failing must not stop the others, but the job must not report
    # success while the results table holds an incomplete picture.
    failures = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_parallel) as pool:
        futures = {pool.submit(scan_one_workspace, ws, rid): ws for ws, rid in ws_run_ids}
        for f in concurrent.futures.as_completed(futures):
            ws = futures[f]
            try:
                failures.extend(f.result() or [])
            except Exception as e:
                loggr.error(f"Fatal error scanning workspace {ws.workspace_id}: {str(e)}")
                print(f"❌ Fatal error for workspace: {ws.workspace_id}: {str(e)}")
                failures.append(f"{ws.workspace_id}: {str(e)}")

    print()
    print("=" * 60)
    if failures:
        print(f"❌ Secret scanning completed with {len(failures)} failure(s):")
        for failure in failures:
            print(f"   • {failure}")
        message = (
            f"Secret scanning failed for {len(failures)} workspace scan(s). "
            f"Results in the table are INCOMPLETE — do not treat the totals as a "
            f"clean bill of health. See the failures listed above."
        )
        loggr.error(message)
        raise RuntimeError(message)

    print(f"✅ Secret scanning completed successfully for {len(ws_run_ids)} workspace(s)")


runTruffleHogScanForAllWorkspaces()
