name: brickhound-sat
display_name: "BrickHound - Databricks Permissions Analysis (SAT)"
description: "Interactive permissions analysis for Databricks (part of SAT)"

# App configuration
config:
  # Entry point for the application
  command:
    - "python"
    - "working_app.py"

  # Environment variables
  # Values from SAT configuration (arunuc.security_analysis)
  env:
    - name: "PORT"
      value: "8501"
    - name: "BRICKHOUND_CATALOG"
      value: "arunuc"
    - name: "BRICKHOUND_SCHEMA"
      value: "security_analysis"
    - name: "WAREHOUSE_ID"
      value: "782228d75bf63e5c"

# Resource requirements
resources:
  # Compute resources
  compute:
    size: "small"

# Health check configuration
health_check:
  path: "/health"
  port: 8501
  timeout: 30

# Dependencies
dependencies:
  # Python packages from requirements.txt will be automatically installed

